// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.3 MyModel.glb -t 
// */

// import * as THREE from 'three'
// import React, { JSX, useMemo } from 'react'
// import { useGLTF } from '@react-three/drei'
// import { GLTF } from 'three-stdlib'
// type GLTFAction = THREE.AnimationAction; // Or just remove the animations property from GLTFResult


// type GLTFResult = GLTF & {
//   nodes: {
//     building1: THREE.Mesh
//     building2: THREE.Mesh
//     building3: THREE.Mesh
//     Home: THREE.Mesh
//     Object_10: THREE.Mesh
//     Object_11: THREE.Mesh
//     Object_12: THREE.Mesh
//     Object_13: THREE.Mesh
//     Object_15: THREE.Mesh
//     Object_16: THREE.Mesh
//     Object_17: THREE.Mesh
//     Object_18: THREE.Mesh
//     Object_19: THREE.Mesh
//     Object_2: THREE.Mesh
//     Object_20: THREE.Mesh
//     Object_22: THREE.Mesh
//     Object_23: THREE.Mesh
//     Object_24: THREE.Mesh
//     Object_25: THREE.Mesh
//     Object_26: THREE.Mesh
//     Object_27: THREE.Mesh
//     Object_28: THREE.Mesh
//     Object_29: THREE.Mesh
//     Object_3: THREE.Mesh
//     Object_30: THREE.Mesh
//     Object_31: THREE.Mesh
//     Object_32: THREE.Mesh
//     Object_33: THREE.Mesh
//     Object_34: THREE.Mesh
//     Object_35: THREE.Mesh
//     Object_36: THREE.Mesh
//     Object_37: THREE.Mesh
//     Object_38: THREE.Mesh
//     Object_39: THREE.Mesh
//     Object_40: THREE.Mesh
//     Object_41: THREE.Mesh
//     Object_42: THREE.Mesh
//     Object_43: THREE.Mesh
//     Object_44: THREE.Mesh
//     Object_45: THREE.Mesh
//     Object_46: THREE.Mesh
//     Object_47: THREE.Mesh
//     Object_48: THREE.Mesh
//     Object_49: THREE.Mesh
//     Object_5: THREE.Mesh
//     Object_50: THREE.Mesh
//     Object_51: THREE.Mesh
//     Object_52: THREE.Mesh
//     Object_6: THREE.Mesh
//     Object_8: THREE.Mesh
//     Object_9: THREE.Mesh
//   }
//   materials: {
//     initialShadingGroup: THREE.MeshStandardMaterial
//     lambert2SG: THREE.MeshStandardMaterial
//   }
//   animations: GLTFAction[]
// }

// export default function Model(props: JSX.IntrinsicElements['group']) {

// // This tells TS: "I know the shape of this model better than you do."
// const { nodes, materials } = useGLTF('/models/MyModel.glb') as unknown as GLTFResult;
// const wireMaterial = useMemo(() => new THREE.MeshBasicMaterial({
//     color: '#ffffff', // White Wireframe
//     wireframe: true,
//   }), []);


// return (
//     <group {...props} dispose={null}>
//       <group rotation={[-Math.PI / 2, 0, 0]}>
//         <mesh geometry={nodes.building1.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.building2.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.building3.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Home.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_10.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_11.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_12.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_13.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_15.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_16.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_17.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_18.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_19.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_2.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_20.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_22.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_23.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_24.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_25.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_26.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_27.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_28.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_29.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_3.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_30.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_31.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_32.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_33.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_34.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_35.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_36.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_37.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_38.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_39.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_40.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_41.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_42.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_43.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_44.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_45.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_46.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_47.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_48.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_49.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_5.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_50.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_51.geometry} material={materials.lambert2SG} />
//         <mesh geometry={nodes.Object_52.geometry} material={materials.lambert2SG} />
//         <mesh geometry={nodes.Object_6.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_8.geometry} material={materials.initialShadingGroup} />
//         <mesh geometry={nodes.Object_9.geometry} material={materials.initialShadingGroup} />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/models/MyModel.glb')












// "use client";

// import * as THREE from 'three'
// import React, { useMemo } from 'react'
// import { useGLTF } from '@react-three/drei'
// import { GLTF } from 'three-stdlib'

// // ... Types thik ache ...

// export default function Model(props: any) {
//   const { nodes } = useGLTF('/models/MyModel.glb') as unknown as GLTFResult;

//   // Industry Standard: Creating a single wireframe material instance
//   const wireMaterial = useMemo(() => new THREE.MeshBasicMaterial({
//     color: '#ffffff', // White Wireframe
//     wireframe: true,
//   }), []);

//   return (
//     <group {...props} dispose={null}>
//       <group rotation={[-Math.PI / 2, 0, 0]}>
//         {/* Loop through all nodes to find meshes and apply wireframe */}
//         {Object.entries(nodes).map(([name, node]) => {
//           if (node instanceof THREE.Mesh) {
//             return (
//               <mesh 
//                 key={name} 
//                 geometry={node.geometry} 
//                 material={wireMaterial} 
//               />
//             )
//           }
//           return null;
//         })}
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/models/MyModel.glb')



"use client";

import * as THREE from 'three'
import React, { useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

// --- 1. Type definition add kora holo (Eta miss hoyechilo) ---
type GLTFResult = GLTF & {
  nodes: { [key: string]: THREE.Object3D } // Generic nodes type
  materials: { [key: string]: THREE.Material }
}

export default function Model(props: any) {
  // --- 2. Ekhon GLTFResult pabe ---
  const { nodes } = useGLTF('/models/MyModel.glb') as unknown as GLTFResult;

  const wireMaterial = useMemo(() => new THREE.MeshBasicMaterial({
    color: '#0a0a0aff', 
    wireframe: true,
    opacity: 0.5,
    transparent: true,
  }), []);

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        {Object.entries(nodes).map(([name, node]) => {
          // Shudhu Mesh gulo ke wireframe material dibo
          if (node instanceof THREE.Mesh) {
            return (
              <mesh 
                key={name} 
                geometry={node.geometry} 
                material={wireMaterial} 
              />
            )
          }
          return null;
        })}
      </group>
    </group>
  )
}

useGLTF.preload('/models/MyModel.glb')